package guessingGame;
import javax.swing.JOptionPane;


/** Game where the user has to guess a number before the computer.
 * @author Connor McFadden
 * */
public class GuessingGame {
    public static void main(String[] args) {
    	int userGuess = 0;
    	int compGuess = 0;
    	int closestLow = 0;
    	int closestHigh = 0;
    	boolean guessTooHigh = false;
    	
    	//Reads in value entered by user and converts to integer
    	int maxNum = Integer.valueOf(JOptionPane.showInputDialog(null, "Enter the highest number to guess", "Guessing Game", 3));
    	int randomNumber = (int) (Math.random()*maxNum+1);
    	closestHigh = maxNum
    			;
    	System.out.println(randomNumber);
    	
    	while (userGuess != randomNumber && compGuess != randomNumber) {
    		userGuess = (int) Integer.valueOf(JOptionPane.showInputDialog(null, "Enter a guess between 1 and 100", "Guessing Game", 3));
    		evaluateGuess(userGuess, randomNumber);
    		if (guessTooHigh) {
    			closestHigh = compGuess;
    			compGuess = guess(closestLow, closestHigh);
    		} else {
    			closestLow = compGuess;
    			compGuess = guess(closestLow, closestHigh);
    		}
    		System.out.println(compGuess);
        	guessTooHigh = evaluateCompGuess(compGuess, randomNumber);
    	}
    }
    
    /**
     * Returns the guess made by the computer
     * 
     * @param lowerValue the lower boundary to guess from
     * @param upperValue the upper boundary to guess from
     * @return the value of the guess made
     * */
    public static int guess(int lowerValue, int upperValue) {
    	return (int) (((upperValue - lowerValue) / 2)+lowerValue);
    }
    
    /**
     * Returns the guess made by the computer
     * 
     * @param userGuess the guess the user has made
     * @param randomNumber the random number generated by the computer
     * */
    public static void evaluateGuess(int userGuess, int randomNumber) {
    	if (userGuess == randomNumber) {
    		JOptionPane.showMessageDialog(null, "Correct, you beat the computer");
    	} else if(userGuess > randomNumber) {
    		JOptionPane.showMessageDialog(null, "Your guess is too high");
    	} else {
    		JOptionPane.showMessageDialog(null, "Your guess is too low");
    	}
    }
    
    /**
     * Returns the guess made by the computer
     * 
     * @param compGuess the guess the computer has made
     * @param randomNumber the random number generated by the computer
     * @return boolean value indicating if computers guess is too high
     * */
    public static boolean evaluateCompGuess(int compGuess, int randomNumber) {
    	if (compGuess == randomNumber) {
    		JOptionPane.showMessageDialog(null, "The computer has guessed the number before you");
    	} else if(compGuess > randomNumber) {
    		return true;
    	} else {
    		return false;
    	}
    	return false;
    }
    
}
